### ISSUE TITLE
子控之前里必须是tableview 吗不能是VC 吗

### ISSUE THREAD

**Issue by liyang521** [Xiexingda/XDPagesView#2]

**Comment by Xiexingda** [comment]
@liyang521 我逻辑里面没有支持vc，那样的话会很麻烦

**Comment by liyang521** [comment]
嗯好的




------------------ 原始邮件 ------------------
发件人: "上北以北"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 晚上7:08
收件人: "Xiexingda/XDPagesView"<XDPagesView@noreply.github.com>; 
抄送: "荒"<1583859369@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Xiexingda/XDPagesView] 子控之前里必须是tableview 吗不能是VC 吗 (#2)




@liyang521 我逻辑里面没有支持vc，那样的话会很麻烦
