### ISSUE TITLE
自定义segment的问题

### ISSUE THREAD

**Issue by zhaohailog** [Xiexingda/XDPagesView#4]
你好，我这边如果想用自定义的segment的话，应该怎么操作，就是不用你自带的。因为产品需要的视觉效果还是不同的，用你自带的实现的话，还是比较复杂的.希望更新一下自定义segment的问题

**Comment by Xiexingda** [comment]
@zhaohailog 把你的segment 放到header上，然后把.needBar = NO, 然后设置一下barMarginTop就可以了

**Comment by Xiexingda** [comment]
重构后没有这个问题了
