### ISSUE TITLE
自定义segment的问题

### ISSUE THREAD

**Issue by zhaohailog** [Xiexingda/XDPagesView#5]
如果我将自定义的segment放在headView上面的话，在顶到顶部的时候，segment的按钮只有点击两次才能点击得到。点击第一次的时候是没有反应的。想问问这个问题应该怎么解决？能不能针对性的修改这个bug呢？但是用你的segment就没有这个问题。

**Comment by Xiexingda** [comment]
@zhaohailog 我不知道你那个segment是怎么实现的，你可以把.needSlideByHeader属性关一下试试
，但这个好像关系不大，你检查一下你的代码看看有没有问题
