### ISSUE TITLE
横向切换到下一页，头部会回到初始状态

### ISSUE THREAD

**Issue by hardworkz** [Xiexingda/XDPagesView#6]
你好，请问你这个组件，如果我滚动到顶部，横向切换到下一页，头部会回到初始状态，如何处理

**Comment by Xiexingda** [comment]
@hardworkz 这个是因为下一页的内容没超过一屏造成的，这个你可以想办法让每页的tableview的contentOffset都超过一屏，或者等我下一个版本的更新

**Comment by Xiexingda** [comment]
@hardworkz 2.0已更新

**Comment by hardworkz** [comment]
好的，非常感谢，我也是这么处理的，生成了一些假数据占位

**Comment by Xiexingda** [comment]
@hardworkz 2.0不需要这么处理了，2.0功能和性能比1.0要强大的多
