### ISSUE TITLE
请教一个需求，分页控制器里面的横向collectionView手势切换

### ISSUE THREAD

**Issue by hardworkz** [Xiexingda/XDPagesView#7]
在横向的分页控制器中，tableviewcell中嵌套横向滚动的collectionview，左右滚动collectionview，当collectionview置左或者置右，无法左右切换分页，这个如何处理会比较好，我尝试使用- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer 这个方法来使得滚动事件可以联动，但是无法控制好左右方向的滚动不带动分页控制器切换，希望能帮忙解答一下，谢谢

**Comment by Xiexingda** [comment]
@hardworkz collectionview.bounces = NO;

**Comment by hardworkz** [comment]
collectionview.bounces = NO;不能实现横向滚动切换，我是监听嵌套的collectionview横向滚动位置来判断是否需要滚动分页的横向滚动，如果不在左右端时滚动就锁定你的pagesView.pagesContener的contentOffsetX(注：我使用的是你之前开发的1.0的版本，2.0版本使用这个方案会导致卡顿)

**Comment by Xiexingda** [comment]
@hardworkz 额，那应该是cell上的手势没有向下传递，如果不处理手势，你可以不锁定内部collection，当collection的contentOffset.x大于最右边时直接jumpToPage到下一页
